# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\lostcorner\Desktop\GUI\yolov5-GUI\main_win\win.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1156, 670)
        mainWindow.setMouseTracking(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/icon/picture.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setStyleSheet("#mainWindow{border:none;}")
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.window = QtWidgets.QGroupBox(self.centralwidget)
        self.window.setStyleSheet("#window{\n"
"     border: 0px solid #42adff;\n"
"     border-radius:5px;\n"
"}")
        self.window.setTitle("")
        self.window.setObjectName("window")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.window)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.top_bar = QtWidgets.QGroupBox(self.window)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 45))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 45))
        self.top_bar.setStyleSheet("#top_bar{\n"
"     background-color: rgba(138, 138, 138, 255);\n"
"     border: 0px solid #42adff;\n"
"     border-left: 0px solid rgba(29, 83, 185, 255);\n"
"     border-right: 0px solid rgba(29, 83, 185, 255);\n"
"     border-bottom: 1px solid rgba(200, 200, 200,100);\n"
"     border-radius:0px;\n"
"}")
        self.top_bar.setTitle("")
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon1 = QtWidgets.QLabel(self.top_bar)
        self.icon1.setMinimumSize(QtCore.QSize(35, 35))
        self.icon1.setMaximumSize(QtCore.QSize(40, 40))
        self.icon1.setStyleSheet("image: url(:/img/icon/trash.png);\n"
"")
        self.icon1.setText("")
        self.icon1.setAlignment(QtCore.Qt.AlignCenter)
        self.icon1.setObjectName("icon1")
        self.horizontalLayout.addWidget(self.icon1)
        self.title = QtWidgets.QLabel(self.top_bar)
        self.title.setEnabled(True)
        self.title.setMinimumSize(QtCore.QSize(200, 0))
        self.title.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 24px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"     color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.horizontalLayout.addWidget(self.title)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.min_max_close = QtWidgets.QHBoxLayout()
        self.min_max_close.setSpacing(0)
        self.min_max_close.setObjectName("min_max_close")
        self.minButton = QtWidgets.QPushButton(self.top_bar)
        self.minButton.setMinimumSize(QtCore.QSize(35, 35))
        self.minButton.setMaximumSize(QtCore.QSize(50, 28))
        self.minButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.minButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/icon/min.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minButton.setIcon(icon1)
        self.minButton.setObjectName("minButton")
        self.min_max_close.addWidget(self.minButton)
        self.maxButton = QtWidgets.QPushButton(self.top_bar)
        self.maxButton.setMinimumSize(QtCore.QSize(35, 35))
        self.maxButton.setMaximumSize(QtCore.QSize(50, 28))
        self.maxButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.maxButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/max.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/还原.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon2.addPixmap(QtGui.QPixmap(":/img/icon/还原.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.maxButton.setIcon(icon2)
        self.maxButton.setCheckable(True)
        self.maxButton.setObjectName("maxButton")
        self.min_max_close.addWidget(self.maxButton)
        self.closeButton = QtWidgets.QPushButton(self.top_bar)
        self.closeButton.setMinimumSize(QtCore.QSize(35, 35))
        self.closeButton.setMaximumSize(QtCore.QSize(50, 28))
        self.closeButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.closeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setObjectName("closeButton")
        self.min_max_close.addWidget(self.closeButton)
        self.horizontalLayout.addLayout(self.min_max_close)
        self.verticalLayout_6.addWidget(self.top_bar)
        self.main = QtWidgets.QHBoxLayout()
        self.main.setSpacing(0)
        self.main.setObjectName("main")
        self.screen = QtWidgets.QGroupBox(self.window)
        self.screen.setStyleSheet("#screen{\n"
"    background-color: rgba(205, 205, 205, 255);\n"
"    border-left: 10px solid rgba(0, 0, 0,100);\n"
"    border-right: 0px solid rgba(29, 83, 185, 255);\n"
"}")
        self.screen.setTitle("")
        self.screen.setObjectName("screen")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.screen)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox_3 = QtWidgets.QGroupBox(self.screen)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 42))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 42))
        self.groupBox_3.setStyleSheet("#groupBox_3{\n"
"border: 0px solid #42adff;\n"
"border-radius:0px;}")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setMinimumSize(QtCore.QSize(100, 40))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_6.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:3px;\n"
"    background:rgba(138, 138, 138, 0);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.fps_label = QtWidgets.QLabel(self.groupBox_3)
        self.fps_label.setMinimumSize(QtCore.QSize(100, 40))
        self.fps_label.setMaximumSize(QtCore.QSize(100, 40))
        self.fps_label.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 20px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"    border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"     color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.fps_label.setText("")
        self.fps_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fps_label.setObjectName("fps_label")
        self.horizontalLayout_6.addWidget(self.fps_label)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.splitter = QtWidgets.QSplitter(self.screen)
        self.splitter.setEnabled(True)
        self.splitter.setStyleSheet("#splitter::handle{background: 1px solid  rgba(200, 200, 200,100);}")
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(10)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(1)
        self.splitter.setObjectName("splitter")
        self.raw_video = Label_click_Mouse(self.splitter)
        self.raw_video.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.raw_video.sizePolicy().hasHeightForWidth())
        self.raw_video.setSizePolicy(sizePolicy)
        self.raw_video.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(36)
        self.raw_video.setFont(font)
        self.raw_video.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.raw_video.setStyleSheet("color: rgb(44, 44, 44);\n"
"")
        self.raw_video.setText("")
        self.raw_video.setScaledContents(False)
        self.raw_video.setAlignment(QtCore.Qt.AlignCenter)
        self.raw_video.setObjectName("raw_video")
        self.out_video = Label_click_Mouse(self.splitter)
        self.out_video.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.out_video.sizePolicy().hasHeightForWidth())
        self.out_video.setSizePolicy(sizePolicy)
        self.out_video.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(36)
        self.out_video.setFont(font)
        self.out_video.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.out_video.setStyleSheet("color: rgb(44, 44, 44);\n"
"")
        self.out_video.setText("")
        self.out_video.setScaledContents(False)
        self.out_video.setAlignment(QtCore.Qt.AlignCenter)
        self.out_video.setObjectName("out_video")
        self.verticalLayout_4.addWidget(self.splitter)
        self.progress = QtWidgets.QGroupBox(self.screen)
        self.progress.setStyleSheet("QGroupBox{\n"
"    background-color: rgba(138, 138, 138, 150);\n"
"    border-radius:10px;\n"
"    margin-bottom:5px;\n"
"}\n"
"")
        self.progress.setAlignment(QtCore.Qt.AlignCenter)
        self.progress.setFlat(False)
        self.progress.setObjectName("progress")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.progress)
        self.horizontalLayout_12.setContentsMargins(-1, -1, 1, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.runButton = QtWidgets.QPushButton(self.progress)
        self.runButton.setMinimumSize(QtCore.QSize(40, 40))
        self.runButton.setStyleSheet("QPushButton {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(223, 223, 223, 0);\n"
"}\n"
"QPushButton::focus{\n"
"    outline: none;\n"
"}\n"
"QPushButton::hover {\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 10px;\n"
"    background-color: rgba(223, 223, 223, 150);}")
        self.runButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/play.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/pause.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/play.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/pause.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/play.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/img/icon/pause.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.runButton.setIcon(icon4)
        self.runButton.setIconSize(QtCore.QSize(30, 30))
        self.runButton.setCheckable(True)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_12.addWidget(self.runButton)
        self.progressBar = QtWidgets.QProgressBar(self.progress)
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 5))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    color: rgb(0, 0, 0); \n"
"    font:12pt; border-radius:2px; \n"
"    text-align:center;     \n"
"    border:none; \n"
"    background-color: rgba(215, 215, 215,100);\n"
"} \n"
"QProgressBar:chunk{ \n"
"    border-radius:0px; \n"
"    background: rgba(55, 55, 55, 200);\n"
"}")
        self.progressBar.setMaximum(1000)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_12.addWidget(self.progressBar)
        self.stopButton = QtWidgets.QPushButton(self.progress)
        self.stopButton.setMinimumSize(QtCore.QSize(40, 40))
        self.stopButton.setStyleSheet("QPushButton {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(223, 223, 223, 0);\n"
"}\n"
"QPushButton::focus{outline: none;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 10px;\n"
"background-color: rgba(223, 223, 223, 150);}")
        self.stopButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/icon/finish.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon5)
        self.stopButton.setIconSize(QtCore.QSize(30, 30))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_12.addWidget(self.stopButton)
        self.verticalLayout_4.addWidget(self.progress)
        self.verticalLayout_4.setStretch(1, 1)
        self.main.addWidget(self.screen)
        self.setting = QtWidgets.QGroupBox(self.window)
        self.setting.setMinimumSize(QtCore.QSize(320, 0))
        self.setting.setMaximumSize(QtCore.QSize(320, 16777215))
        self.setting.setStyleSheet("#setting{\n"
"    background-color: rgba(138, 138, 138, 255);\n"
"}\n"
"")
        self.setting.setTitle("")
        self.setting.setObjectName("setting")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.setting)
        self.verticalLayout_8.setSpacing(11)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.setting)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 42))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 42))
        self.groupBox_2.setStyleSheet("#groupBox_2{\n"
"border: 0px solid #42adff;\n"
"border-radius:0px;}")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_35.setContentsMargins(2, 0, 0, 0)
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(35, 35))
        self.label.setStyleSheet("image: url(:/img/icon/setting.png);")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_35.addWidget(self.label)
        self.label_title = QtWidgets.QLabel(self.groupBox_2)
        self.label_title.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_title.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 22px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:9px;\n"
"    background:rgba(66, 195, 255, 0);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_35.addWidget(self.label_title)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem2)
        self.resetButton = QtWidgets.QPushButton(self.groupBox_2)
        self.resetButton.setMinimumSize(QtCore.QSize(75, 28))
        self.resetButton.setStyleSheet("QPushButton {\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:5px;\n"
"    background:rgba(205, 205, 205, 200);\n"
"    color: rgb(44, 44, 44);\n"
"}")
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_35.addWidget(self.resetButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem3)
        self.verticalLayout_8.addWidget(self.groupBox_2)
        self.model_select = QtWidgets.QHBoxLayout()
        self.model_select.setObjectName("model_select")
        self.label_model_select = QtWidgets.QLabel(self.setting)
        self.label_model_select.setMinimumSize(QtCore.QSize(80, 28))
        self.label_model_select.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_model_select.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:5px;\n"
"    background:rgba(205, 205, 205, 200);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_model_select.setAlignment(QtCore.Qt.AlignCenter)
        self.label_model_select.setObjectName("label_model_select")
        self.model_select.addWidget(self.label_model_select)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.model_select.addItem(spacerItem4)
        self.Layout_comboBox = QtWidgets.QHBoxLayout()
        self.Layout_comboBox.setObjectName("Layout_comboBox")
        self.comboBox = QtWidgets.QComboBox(self.setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(130, 28))
        self.comboBox.setMaximumSize(QtCore.QSize(16777215, 28))
        self.comboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("QComboBox QAbstractItemView {\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    background:rgba(200, 200, 200,150);\n"
"    selection-background-color: rgba(200, 200, 200,50);\n"
"    color: rgb(44, 44, 44);\n"
"    outline:none;\n"
"    border:none;\n"
"}\n"
"QComboBox{\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: rgb(44, 44, 44);\n"
"    border-width:0px;\n"
"    border-color:white;\n"
"    border-style:solid;\n"
"    background-color: rgba(205, 205, 205, 0);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    margin-top:5;\n"
"    right:10px;\n"
"    height:20;\n"
"    background:rgba(255,255,255,0);\n"
"    border-image: url(:/img/icon/bottom.png);\n"
"}\n"
"\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBox.setIconSize(QtCore.QSize(20, 20))
        self.comboBox.setDuplicatesEnabled(False)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Layout_comboBox.addWidget(self.comboBox)
        self.model_select.addLayout(self.Layout_comboBox)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.model_select.addItem(spacerItem5)
        self.verticalLayout_8.addLayout(self.model_select)
        self.file_select = QtWidgets.QHBoxLayout()
        self.file_select.setObjectName("file_select")
        self.label_fileSelect = QtWidgets.QLabel(self.setting)
        self.label_fileSelect.setMinimumSize(QtCore.QSize(80, 28))
        self.label_fileSelect.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_fileSelect.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:5px;\n"
"    background:rgba(205, 205, 205, 200);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_fileSelect.setAlignment(QtCore.Qt.AlignCenter)
        self.label_fileSelect.setObjectName("label_fileSelect")
        self.file_select.addWidget(self.label_fileSelect)
        self.Layout_fileButton = QtWidgets.QHBoxLayout()
        self.Layout_fileButton.setObjectName("Layout_fileButton")
        self.fileButton = QtWidgets.QPushButton(self.setting)
        self.fileButton.setMinimumSize(QtCore.QSize(55, 28))
        self.fileButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.fileButton.setStyleSheet("QPushButton{font-family: \"Microsoft YaHei\";\n"
"font-size: 14px;\n"
"font-weight: bold;\n"
"color:white;\n"
"text-align: center center;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"padding-top: 4px;\n"
"padding-bottom: 4px;\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-color: rgba(255, 255, 255, 255);\n"
"border-radius: 3px;\n"
"background-color: rgba(200, 200, 200,0);}\n"
"\n"
"QPushButton:focus{outline: none;}\n"
"\n"
"QPushButton::pressed{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"\n"
"QPushButton::disabled{font-family: \"Microsoft YaHei\";\n"
"                     font-size: 14px;\n"
"                     font-weight: bold;\n"
"                     color:rgb(200,200,200);\n"
"                     text-align: center center;\n"
"                     padding-left: 5px;\n"
"                     padding-right: 5px;\n"
"                     padding-top: 4px;\n"
"                     padding-bottom: 4px;\n"
"                     border-style: solid;\n"
"                     border-width: 0px;\n"
"                     border-color: rgba(255, 255, 255, 255);\n"
"                     border-radius: 3px;\n"
"                     background-color:  #bf513b;}\n"
"QPushButton::hover {\n"
"border-style: solid;\n"
"border-width: 0px;\n"
"border-radius: 0px;\n"
"background-color: rgba(48,148,243,80);}")
        self.fileButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/icon/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fileButton.setIcon(icon6)
        self.fileButton.setObjectName("fileButton")
        self.Layout_fileButton.addWidget(self.fileButton)
        self.file_select.addLayout(self.Layout_fileButton)
        self.verticalLayout_8.addLayout(self.file_select)
        self.IoU = QtWidgets.QHBoxLayout()
        self.IoU.setSpacing(4)
        self.IoU.setObjectName("IoU")
        self.label_IoU = QtWidgets.QLabel(self.setting)
        self.label_IoU.setMinimumSize(QtCore.QSize(80, 28))
        self.label_IoU.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_IoU.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:5px;\n"
"    background:rgba(205, 205, 205, 200);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_IoU.setAlignment(QtCore.Qt.AlignCenter)
        self.label_IoU.setObjectName("label_IoU")
        self.IoU.addWidget(self.label_IoU)
        self.Layout_IoU = QtWidgets.QHBoxLayout()
        self.Layout_IoU.setSpacing(5)
        self.Layout_IoU.setObjectName("Layout_IoU")
        self.iouSpinBox = QtWidgets.QDoubleSpinBox(self.setting)
        self.iouSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.iouSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.iouSpinBox.setAutoFillBackground(False)
        self.iouSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    color:white;\n"
"    font-size: 14px;\n"
"    font-family: \"Microsoft YaHei UI\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgba(44, 44, 44,100);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"    background:rgba(205, 205, 205, 0);\n"
"    border-image: url(:/img/icon/arrow-down.png);\n"
"}\n"
"QDoubleSpinBox::down-button::hover{\n"
"    background:rgba(205, 205, 205, 100);    \n"
"    border-image: url(:/img/icon/arrow-down.png);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"    background:rgba(205, 205, 205, 0);\n"
"    border-image: url(:/img/icon/arrow-up.png);\n"
"}\n"
"QDoubleSpinBox::up-button::hover{\n"
"     background:rgba(205, 205, 205, 100);\n"
"     border-image: url(:/img/icon/arrow-up.png);\n"
"}\n"
"")
        self.iouSpinBox.setMaximum(1.0)
        self.iouSpinBox.setSingleStep(0.01)
        self.iouSpinBox.setProperty("value", 0.45)
        self.iouSpinBox.setObjectName("iouSpinBox")
        self.Layout_IoU.addWidget(self.iouSpinBox)
        self.iouSlider = QtWidgets.QSlider(self.setting)
        self.iouSlider.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/dot.png);\n"
"     width:12px;\n"
"     margin: -5px -5px -5px -5px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.iouSlider.setMaximum(100)
        self.iouSlider.setProperty("value", 45)
        self.iouSlider.setOrientation(QtCore.Qt.Horizontal)
        self.iouSlider.setObjectName("iouSlider")
        self.Layout_IoU.addWidget(self.iouSlider)
        self.IoU.addLayout(self.Layout_IoU)
        self.verticalLayout_8.addLayout(self.IoU)
        self.confidence = QtWidgets.QHBoxLayout()
        self.confidence.setSpacing(4)
        self.confidence.setObjectName("confidence")
        self.label_conf = QtWidgets.QLabel(self.setting)
        self.label_conf.setMinimumSize(QtCore.QSize(80, 28))
        self.label_conf.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:5px;\n"
"    background:rgba(205, 205, 205, 200);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_conf.setAlignment(QtCore.Qt.AlignCenter)
        self.label_conf.setObjectName("label_conf")
        self.confidence.addWidget(self.label_conf)
        self.Layout_confidence = QtWidgets.QHBoxLayout()
        self.Layout_confidence.setSpacing(5)
        self.Layout_confidence.setObjectName("Layout_confidence")
        self.confSpinBox = QtWidgets.QDoubleSpinBox(self.setting)
        self.confSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.confSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.confSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.confSpinBox.setStyleSheet("QDoubleSpinBox{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    color:white;\n"
"    font-size: 14px;\n"
"    font-family: \"Microsoft YaHei UI\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgba(44, 44, 44,100);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QDoubleSpinBox::down-button{\n"
"    background:rgba(205, 205, 205, 0);\n"
"    border-image: url(:/img/icon/arrow-down.png);\n"
"}\n"
"QDoubleSpinBox::down-button::hover{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    border-image: url(:/img/icon/arrow-down.png);\n"
"}\n"
"\n"
"QDoubleSpinBox::up-button{\n"
"    background:rgba(205, 205, 205, 0);\n"
"    border-image: url(:/img/icon/arrow-up.png);\n"
"}\n"
"QDoubleSpinBox::up-button::hover{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    border-image: url(:/img/icon/arrow-up.png);}\n"
"")
        self.confSpinBox.setMaximum(1.0)
        self.confSpinBox.setSingleStep(0.01)
        self.confSpinBox.setProperty("value", 0.25)
        self.confSpinBox.setObjectName("confSpinBox")
        self.Layout_confidence.addWidget(self.confSpinBox)
        self.confSlider = QtWidgets.QSlider(self.setting)
        self.confSlider.setStyleSheet("QSlider{\n"
"border-color: #bcbcbc;\n"
"color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"     border: 1px solid #999999;                             \n"
"     height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"     left: 5px; right: 5px; \n"
" }\n"
"QSlider::handle:horizontal {                               \n"
"     border: 0px ; \n"
"     border-image: url(:/img/icon/dot.png);\n"
"     width:12px;\n"
"     margin: -5px -5px -5px -5px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.confSlider.setMaximum(100)
        self.confSlider.setProperty("value", 25)
        self.confSlider.setOrientation(QtCore.Qt.Horizontal)
        self.confSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.confSlider.setObjectName("confSlider")
        self.Layout_confidence.addWidget(self.confSlider)
        self.confidence.addLayout(self.Layout_confidence)
        self.verticalLayout_8.addLayout(self.confidence)
        self.delay = QtWidgets.QVBoxLayout()
        self.delay.setSpacing(4)
        self.delay.setObjectName("delay")
        self.layout_setting = QtWidgets.QHBoxLayout()
        self.layout_setting.setObjectName("layout_setting")
        self.label_8 = QtWidgets.QLabel(self.setting)
        self.label_8.setMinimumSize(QtCore.QSize(80, 28))
        self.label_8.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_8.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"     border-radius:5px;\n"
"    background:rgba(205, 205, 205, 200);\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.layout_setting.addWidget(self.label_8)
        self.checkBox = QtWidgets.QCheckBox(self.setting)
        self.checkBox.setStyleSheet("\n"
"QCheckBox{\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"\n"
"QCheckBox::indicator{\n"
"    width: 17px;\n"
"    height: 17px;\n"
"    left:10px\n"
"\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    image: url(:/img/icon/button-off.png);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    image: url(:/img/icon/button-on.png);\n"
"}\n"
"")
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.layout_setting.addWidget(self.checkBox)
        self.delay.addLayout(self.layout_setting)
        self.layout_slide = QtWidgets.QHBoxLayout()
        self.layout_slide.setSpacing(5)
        self.layout_slide.setObjectName("layout_slide")
        self.rateSpinBox = QtWidgets.QSpinBox(self.setting)
        self.rateSpinBox.setMinimumSize(QtCore.QSize(50, 0))
        self.rateSpinBox.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rateSpinBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.rateSpinBox.setStyleSheet("QSpinBox{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    color:white;\n"
"    font-size: 14px;\n"
"    font-family: \"Microsoft YaHei UI\";\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgba(44, 44, 44,100);\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QSpinBox::down-button{\n"
"    background:rgba(205, 205, 205, 0);\n"
"    border-image: url(:/img/icon/arrow-down.png);\n"
"}\n"
"QDoubleSpinBox::down-button::hover{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    border-image: url(:/img/icon/arrow-down.png);\n"
"}\n"
"QSpinBox::up-button{\n"
"    background:rgba(205, 205, 205, 0);\n"
"    border-image: url(:/img/icon/arrow-up.png);\n"
"}\n"
"QSpinBox::up-button::hover{\n"
"    background:rgba(205, 205, 205, 100);\n"
"    border-image: url(:/img/icon/arrow-up.png);\n"
"}\n"
"")
        self.rateSpinBox.setMinimum(1)
        self.rateSpinBox.setMaximum(20)
        self.rateSpinBox.setSingleStep(1)
        self.rateSpinBox.setProperty("value", 1)
        self.rateSpinBox.setObjectName("rateSpinBox")
        self.layout_slide.addWidget(self.rateSpinBox)
        self.rateSlider = QtWidgets.QSlider(self.setting)
        self.rateSlider.setStyleSheet("QSlider{\n"
"    border-color: #bcbcbc;\n"
"    color:#d9d9d9;\n"
"}\n"
"QSlider::groove:horizontal {                                \n"
"    border: 1px solid #999999;                             \n"
"    height: 3px;                                           \n"
"    margin: 0px 0;                                         \n"
"    left: 10px; right: 5px; \n"
"}\n"
"QSlider::handle:horizontal {                               \n"
"    border: 0px ; \n"
"    border-image: url(:/img/icon/dot.png);\n"
"    width:12px;\n"
"    margin: -5px -5px -5px -5px;                  \n"
"} \n"
"QSlider::add-page:horizontal{\n"
"background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #d9d9d9, stop:0.25 #d9d9d9, stop:0.5 #d9d9d9, stop:1 #d9d9d9); \n"
"\n"
"}\n"
"QSlider::sub-page:horizontal{                               \n"
" background: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #373737, stop:0.25 #373737, stop:0.5 #373737, stop:1 #373737);                     \n"
"}")
        self.rateSlider.setMinimum(1)
        self.rateSlider.setMaximum(20)
        self.rateSlider.setSingleStep(1)
        self.rateSlider.setPageStep(1)
        self.rateSlider.setProperty("value", 1)
        self.rateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rateSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.rateSlider.setObjectName("rateSlider")
        self.layout_slide.addWidget(self.rateSlider)
        self.delay.addLayout(self.layout_slide)
        self.verticalLayout_8.addLayout(self.delay)
        self.result_box = QtWidgets.QGridLayout()
        self.result_box.setObjectName("result_box")
        self.resultWidget = QtWidgets.QListWidget(self.setting)
        self.resultWidget.setStyleSheet("QListWidget{\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"    border: 2px solid rgba(205, 205, 205,100);\n"
"    border-radius:0px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-size: 16px;\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.resultWidget.setObjectName("resultWidget")
        self.result_box.addWidget(self.resultWidget, 1, 0, 1, 1)
        self.label_result = QtWidgets.QLabel(self.setting)
        self.label_result.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 18px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: bold;\n"
"    border-radius:9px;\n"
"    color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.label_result.setObjectName("label_result")
        self.result_box.addWidget(self.label_result, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.result_box)
        self.main.addWidget(self.setting)
        self.verticalLayout_6.addLayout(self.main)
        self.status_bar = QtWidgets.QGroupBox(self.window)
        self.status_bar.setMinimumSize(QtCore.QSize(0, 30))
        self.status_bar.setMaximumSize(QtCore.QSize(16777215, 30))
        self.status_bar.setStyleSheet("#status_bar{\n"
"background-color: rgba(138, 138, 138, 255);\n"
"border: 0px solid #42adff;\n"
"border-left: 0px solid rgba(29, 83, 185, 255);\n"
"border-right: 0px solid rgba(29, 83, 185, 255);\n"
"border-top: 1px solid rgba(200, 200, 200,100);\n"
"border-radius:0px;}")
        self.status_bar.setTitle("")
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.status_bar)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.statistic_label = QtWidgets.QLabel(self.status_bar)
        self.statistic_label.setMouseTracking(False)
        self.statistic_label.setStyleSheet("QLabel\n"
"{\n"
"    font-size: 16px;\n"
"    font-family: \"Microsoft YaHei\";\n"
"    font-weight: light;\n"
"         border-radius:9px;\n"
"        background:rgba(66, 195, 255, 0);\n"
"color: rgb(44, 44, 44);\n"
"}\n"
"")
        self.statistic_label.setText("")
        self.statistic_label.setObjectName("statistic_label")
        self.horizontalLayout_10.addWidget(self.statistic_label)
        self.verticalLayout_6.addWidget(self.status_bar)
        self.verticalLayout_2.addWidget(self.window)
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Yolov5垃圾检测"))
        self.title.setText(_translate("mainWindow", "Yolov5垃圾检测"))
        self.label_6.setText(_translate("mainWindow", "显示界面"))
        self.label_title.setText(_translate("mainWindow", "设置"))
        self.resetButton.setText(_translate("mainWindow", "重置参数"))
        self.label_model_select.setText(_translate("mainWindow", "模型选择"))
        self.comboBox.setCurrentText(_translate("mainWindow", "yolov5s.pt"))
        self.comboBox.setItemText(0, _translate("mainWindow", "yolov5s.pt"))
        self.comboBox.setItemText(1, _translate("mainWindow", "yolov5m.pt"))
        self.comboBox.setItemText(2, _translate("mainWindow", "yolov5l.pt"))
        self.comboBox.setItemText(3, _translate("mainWindow", "yolov5x.pt"))
        self.label_fileSelect.setText(_translate("mainWindow", "文件选择"))
        self.fileButton.setToolTip(_translate("mainWindow", "文件"))
        self.label_IoU.setText(_translate("mainWindow", "IoU"))
        self.label_conf.setText(_translate("mainWindow", "置信度"))
        self.label_8.setText(_translate("mainWindow", "帧间延时"))
        self.checkBox.setText(_translate("mainWindow", "启用"))
        self.label_result.setText(_translate("mainWindow", "结果统计"))
from MouseLabel import Label_click_Mouse
import apprcc_rc
